---
# 1. 디렉토리 생성
- name: Ensure manifest directories exist on remote
  file:
    path: "/home/{{ ansible_user }}/k8s/{{ item }}"
    state: directory
  loop:
    - app
    - monitoring

# 2. APP 매니페스트 복사
- name: Copy app manifests
  copy:
    src: files/manifests.yaml
    dest: "/home/{{ ansible_user }}/k8s/app/manifests.yaml"

# 3. Prometheus/Alertmanager 템플릿 배포
- name: Copy Monitoring manifests
  template:
    src: "k8s/{{ item }}" 
    dest: "/home/{{ ansible_user }}/k8s/monitoring/{{ item | replace('.j2', '') }}"
  loop:
    - prometheus.yaml.j2
    - alertmanager.yaml.j2
    - alert-rules.yaml.j2

# 4. kube-state-metrics 설치
- name: Apply kube-state-metrics
  command: >
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/kube-state-metrics/v2.10.1/examples/standard/{{ item }}
  loop:
    - service-account.yaml
    - cluster-role.yaml
    - cluster-role-binding.yaml
    - deployment.yaml
    - service.yaml
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"

# 5. 모든 매니페스트 적용
- name: Apply all local K8s manifests
  command: "kubectl apply -R -f /home/{{ ansible_user }}/k8s/"
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"

# 6. 앱 롤아웃 재시작
- name: Rollout restart deployment
  command: "kubectl rollout restart deployment/cat-web-deployment"
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"