---
- name: Ensure manifest directories exist on remote
  file:
    path: /home/{{ ansible_user }}/k8s/{{ item }}
    state: directory
  loop:
    - app
    - monitoring

- name: Copy app manifests
  copy:
    src: files/manifests.yaml
    dest: /home/{{ ansible_user }}/k8s/app/manifests.yaml

- name: Apply monitoring manifests (Templates)
  template:
    src: k8s/alertmanager.yaml.j2
    dest: /home/{{ ansible_user }}/k8s/monitoring/alertmanager.yaml


- name: Apply kube-state-metrics
  command: >
    kubectl apply -k https://github.com/kubernetes/kube-state-metrics/examples/standard?ref=v2.10.1
  environment:
    KUBECONFIG: /home/{{ ansible_user }}/.kube/config

- name: Apply all K8s manifests
  command: >
    kubectl apply -R -f /home/{{ ansible_user }}/k8s/
  environment:
    KUBECONFIG: /home/{{ ansible_user }}/.kube/config

- name: Rollout restart deployment
  command: >
    kubectl rollout restart deployment/cat-web-deployment
  environment:
    KUBECONFIG: /home/{{ ansible_user }}/.kube/config