---
- name: Check if k3s is installed
  stat:
    path: /usr/local/bin/k3s
  register: k3s_bin

- name: Install k3s (Disable Traefik)
  shell: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik" sh -
  when: not k3s_bin.stat.exists

- name: Ensure k3s is updated to disable traefik
  shell: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik" sh -
  when: k3s_bin.stat.exists

- name: Wait for k3s to be ready
  wait_for:
    path: /etc/rancher/k3s/k3s.yaml
    state: present

- name: Setup kubeconfig for user
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    mode: '0755'

- name: Copy kubeconfig
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "/home/{{ ansible_user }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_user }}"
    mode: '0600'

- name: Update kubeconfig server address
  replace:
    path: "/home/{{ ansible_user }}/.kube/config"
    regexp: '127.0.0.1'
    replace: 'localhost'
